name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey! Thanks for creating your first issue on Ozon3!'
        pr-message: 'Awesome work with your first PR for Ozon3! We will review your PR soon :)'
